smoke test update

diff --git a/.github/workflows/smoke-test.yml b/.github/workflows/smoke-test.yml
--- a/.github/workflows/smoke-test.yml
+++ b/.github/workflows/smoke-test.yml
@@ -103,5 +103,7 @@ jobs:
           commit_message: "Update smoke test badge"
 
       - name: Fail job on smoke test errors
-        if: ${{ steps.smoke.outcome == 'failure' && steps.badge.outputs.exit_code != '2' }}
-        run: exit 1
+        if: ${{ steps.smoke.outcome == 'failure' }}
+        run: |
+          echo "Smoke test failed with exit code ${{ steps.badge.outputs.exit_code }}"
+          exit 1
